# bottom
bottom:
  qianghua : [1020, 650, 1060, 670]
  shixiu: [1022, 285, 1091, 350]
  sheding: [672, 580, 935, 651]
  xuandui: [1186, 61, 1225, 98]
  chuji: [533, 625, 749, 682]
  xingdongkaishi: [1088, 545, 1198, 627]
  zhandouchengguo: [63, 54, 155, 87]
  zaiwanyici: [660, 482, 929, 552]
  shengdianmoshi_img: [389, 413, 656, 443]
  shengdianmoshi_bottom: [410, 428, 410, 428]
  baoshi: [810, 371, 876, 432]
  xiangqing: [906, 522, 1080, 570]
  zhandou: [660, 482, 929, 552]
  max: [826, 400, 876, 451]
  tuichu: [358, 517, 619, 591]
  ditu: [1094, 119, 1094, 119]
  skip: [1108, 75, 1145, 119]

compare:
  xingdongkaishi: [0, 0, 110, 82]
  value: 0.1

dp:
  location: [
    [159, 626, 213, 641],
    [342, 626, 396, 641],
    [526, 626, 577, 641],
    [692, 629, 735, 641],
    [844, 629, 887, 641],
    [997, 629, 1040, 641]
  ]
keyboard:
  down: [40, 0x50]
  up: [38, 0x48]
  left: [37, 0x4b]
  right: [39, 0x4d]
  S: [83, 0x1f]
  W: [87, 0x11]
  D: [68, 0x20]
  enter: [13, 0x1c]
  O: [79, 0x18]
  A: [65, 0x1e]
  5: [53, 0x06]
  2: [50, 0x03]
  1: [49, 0x02]
  3: [51, 0x04]
  4: [52, 0x05]
  6: [54, 0x07]

daily:
  arachnelineA:
    # start: [B-qianghua, B-baoshi, K-W, K-enter, K-enter, K-enter, K-enter]
    start: [B-qianghua, B-baoshi, K-W, K-enter, K-enter, K-enter, B-max, K-enter]
    select: 1
    skill-list: [
      [[1, 1, 2, 0], [2, 2, 0, 0], [3, 3, 2, 0]],
      [[1, 1, 3, 0], [2, 2, 0, 0], [3, 3, 0, 0]],
      [[1, 1, 4, 3], [2, 2, 4, 3], [3, 3, 1, 0]],
      [[1, 4, 1, 0], [2, 2, 0, 0], [3, 3, 4, 0]],
    ]
    end: [U-tuichu-enter]
  
  shixiu:
    start: [B-qianghua, B-shixiu, B-sheding]
    select: 4
    # [几号位，上谁， 放几号技能， 放给谁] 0代表不放技能, 
    skill-list: [
      [[1, 1, 0, 0], [2, 5, 2, 0], [3, 3, 2, 2]],
      [[1, 1, 1, 0], [2, 2, 3, 0], [3, 6, 2, 2]]
      ]
    end: [K-enter, W-zhandouchengguo, B-zhandouchengguo, B-zhandouchengguo, W-shengdianmoshi_img, B-shengdianmoshi_bottom, B-zaiwanyici]

score:
  59B:
    start: []
    # 几号编队
    select: 5
    skill-list: [
      [[1, 1, 0, 0], [2, 2, 0, 0], [3, 3, 0, 0]],
      [[1, 1, 2, 0], [2, 2, 0, 0], [3, 3, 0, 0]],
      [[1, 1, 0, 0], [2, 2, 0, 0], [3, 5, 0, 0]],
      [[1, 1, 1, 0], [2, 2, 1, 1], [3, 5, 4, 1]],
      [[1, 3, 4, 3], [2, 4, 1, 0], [3, 3, 4, 0]],
      [[1, 3, 0, 0], [2, 4, 5, 0], [3, 5, 1, 0]],
      [[1, 1, 0, 0], [2, 2, 4, 0], [3, 3, 1, 0]],
      [[1, 1, 3, 0], [2, 2, 0, 0], [3, 5, 0, 0]],
      [[1, 1, 0, 0], [2, 2, 0, 0], [3, 3, 0, 0]],
      [[1, 1, 0, 0], [2, 2, 0, 0], [3, 3, 0, 0]],
      [[1, 1, 3, 0], [2, 2, 2, 0], [3, 3, 4, 1]],
      [[1, 3, 0, 0], [2, 4, 0, 0], [3, 5, 3, 0]],
      [['O']],
      [[1, 4, 1, 5], [2, 4, 1, 0], [3, 4, 1, 0]],
      [[1, 1, 1, 5], [2, 2, 1, 0], [3, 3, 2, 0]],
      [[1, 3, 1, 0], [2, 2, 4, 5], [3, 5, 4, 0]]
    ]
    end: []

skfeather:
  stage1-skill-list: [
    [[1, 1, 1, 0], [2, 3, 0, 0], [3, 4, 0, 0]],
    [[1, 1, 0, 0], [2, 3, 4, 0], [3, 6, 0, 0]],
    [[1, 4, 2, 0], [2, 6, 2, 0], [3, 5, 0, 0]],
    [[1, 4, 1, 0], [2, 2, 0, 0], [3, 6, 0, 0]],
    [[1, 1, 1, 0], [2, 2, 0, 0], [3, 3, 3, 0]],
    [[1, 3, 0, 0], [2, 2, 0, 0], [3, 3, 0, 0]],
    [[1, 5, 2, 5], [2, 2, 1, 5], [3, 3, 1, 0]],
    [[1, 3, 1, 0], [2, 4, 0, 0], [3, 4, 0, 0]],
    [[1, 4, 4, 0], [2, 6, 1, 0], [3, 5, 1, 0]]
  ]
  stage2-skill-list: [
    [[1, 4, 3, 0], [2, 5, 1, 0], [3, 6, 1, 0]],
    [[1, 5, 2, 0], [2, 2, 0, 0], [3, 3, 0, 0]],
    [[1, 4, 1, 6], [2, 5, 1, 0], [3, 'max1', [2, 3, 4], 0]],
    [[1, 6, 3, 0], [2, 'max1', [1, 2, 3, 4, 5], 0], [3, 'max2', [1, 2, 3, 4, 5], 0]],
    [[1, 6, 0, 0], [2, 4, 0, 0], [3, 4, 0, 0]],
    [['O']],
    [[1, 1, 1, 6], [2, 2, 1, 0], [3, 3, 1, 0]],
    [[1, 1, 1, 6], [2, 2, 1, 0], [3, 6, 3, 0]],
    [[1, 6, 0, 0], [2, 2, 0, 0], [3, 6, 1, 6]],
    [[1, 3, 0, 0], [2, 2, 0, 0], [3, 6, 1, 0]]
  ]
  stage3-skill-list: [
    [[1, 5, 3, 0], [2, 3, 0, 0], [3, 3, 0, 0]],
    [[1, 4, 0, 0], [2, 6, 2, 0], [3, 5, 0, 0]],
    [[1, 1, 0, 0], [2, 4, 3, 0], [3, 6, 0, 0]],
    [[1, 1, 0, 0], [2, 2, 0, 0], [3, 3, 3, 0]],
    [[1, 3, 0, 0], [2, 2, 0, 0], [3, 3, 2, 0]],
    [[1, 6, 2, 6], [2, 2, 1, 6], [3, 3, 0, 0]],
    [[1, 1, 4, 0], [2, 5, 1, 0], [3, 6, 1, 0]]
  ]
  stage4-skill-list: [
    [[1, 6, 1, 0], [2, 'max1', [1, 3, 4, 5], 0], [3, 'max2', [1, 3, 4, 5], 0]],
    [[1, 'max1', [0, 1, 3, 4, 5], 0], [2, 'max2', [0, 1, 3, 4, 5], 0], [3, 'max3', [0, 1, 3, 4, 5], 0]],
    [[1, 1, 1, 0], [2, 'max1', [1, 3, 4, 5], 0], [3, 'max2', [1, 3, 4, 5], 0]],
    [['O']],
    [[1, 6, 0, 0], [2, 2, 1, 0], [3, 3, 3, 0]],
    [[1, 2, 1, 0], [2, 3, 3, 0], [3, 6, 2, 0]],
    [[1, 6, 3, 0], [2, 6, 0, 0], [3, 6, 1, 0]]
  ]
  stage5-skill-list: [
    [[1, 6, 2, 0], [2, 4, 1, 0], [3, 3, 0, 0]],
    [[1, 1, 0, 0], [2, 5, 4, 0], [3, 6, 1, 0]],
    [[1, 1, 0, 0], [2, 5, 1, 0], [3, 6, 3, 0]],
    [[1, 1, 2, 0], [2, 3, 2, 0], [3, 4, 4, 0]],
    [[1, 1, 1, 0], [2, 4, 1, 0], [3, 4, 0, 0]],
    [[1, 5, 1, 3], [2, 3, 3, 0], [3, 6, 2, 2]],
    [['O']],
    [[1, 5, 3, 0], [2, 4, 1, 0], [3, 3, 4, 0]],
    [[1, 1, 3, 0], [2, 2, 1, 0], [3, 3, 4, 0]],
    [[1, 5, 1, 4], [2, 4, 1, 0], [3, 3, 2, 2]]
  ]